#!/bin/sh -e
# script by Manfred Bergmann in 2006
#

APP=sword
VERS=1.6.0-svn
BDIR=`pwd`

DEBUG=0
FAT=0
PPC=0
INTEL=0

PREFIX=

# check commandline
while [ "$1" ]; do
	if [ "$1" = "debug" ]; then
		DEBUG=1
		echo "building debug version"
	fi
	if [ "$1" = "fat" ]; then
		FAT=1
		PPC=1
		INTEL=1
		echo "building fat version"
	fi
	if [ "$1" = "ppc" ]; then
		PPC=1
		echo "building ppc version"
	else
		PPC=0
	fi
	if [ "$1" = "intel" ]; then
		INTEL=1
		echo "building intel version"
	else
		INTEL=0
	fi
	if [ "$1" = "-p" ]; then
	    shift
	    PREFIX="$1"
	    echo "have prefix: $PREFIX"
	fi
	shift
done

# using seperate build dirs and building in them doesn't work with sword
SWORDBUILD=$BDIR/build_full_svn

# Create install dirs if they doesn't exist
if [ ! -d $SWORDBUILD ]; then
	mkdir -p $SWORDBUILD
fi

if [ "$PREFIX" = "" ]; then
    PREFIX="$SWORDBUILD/install_dir"
fi

# delete old source dir
#/bin/rm -rf $APP-$VERS
# ungzip src
#gzip -dc $APP-$VERS.tar.gz | tar xvf -
# ==> we use svn trunk here

# add icu tools to path
export PATH="$PATH:/opt/icu-3.6/bin"
export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:/opt/icu-3.6/lib"

# build stuff
if [ $PPC -eq 1 ]; then
    echo "building ppc version of library..."
	cd sword-trunk
	#make distclean
	./autogen.sh
	export CC=gcc
	export CXX=g++
	export SDK=/Developer/SDKs/MacOSX10.5.sdk
	if [ $DEBUG -eq 1 ]; then
		export CFLAGS="-O0 -g -arch ppc -mmacosx-version-min=10.5 -I/sw/include -isysroot $SDK"
	else
	    export CFLAGS="-O2 -g0 -arch ppc -mmacosx-version-min=10.5 -I/sw/include -isysroot $SDK" 
	fi
	export CXXFLAGS="$CFLAGS"
	export LDFLAGS="-isysroot $SDK -Wl,-syslibroot,$SDK"
	./configure --prefix=$PREFIX --with-zlib --with-icu --with-conf --with-curl
	make all install
	make clean
	cd $BDIR
    echo "building ppc version of library...done"
else
    # then build intel version
	#cd $APP-$VERS
	cd sword-trunk
	make clean		
	#make distclean
	./autogen.sh
	export CC=gcc
	export CXX=g++
	export SDK=/Developer/SDKs/MacOSX10.5.sdk
	if [ $DEBUG -eq 1 ]; then
		export CFLAGS="-O0 -g -arch i686 -mmacosx-version-min=10.5 -I/sw/include -isysroot $SDK"
	else
	    export CFLAGS="-O2 -g0 -arch i686 -mmacosx-version-min=10.5 -I/sw/include -isysroot $SDK" 
	fi
	export CXXFLAGS="$CFLAGS"
	export LDFLAGS="-isysroot $SDK -Wl,-syslibroot,$SDK"
	./configure --prefix=$PREFIX --with-zlib --with-icu --with-conf --with-curl
	make all install
	make clean		
	cd $BDIR
fi
