ibtool --export-strings-file About.strings About.xib
ibtool --export-strings-file BibleCombiView.strings BibleCombiView.xib
ibtool --export-strings-file BibleView.strings BibleView.xib
ibtool --export-strings-file BookmarkManagerUI.strings BookmarkManagerUI.xib
ibtool --export-strings-file CommentaryView.strings CommentaryView.xib
ibtool --export-strings-file ConfirmationDialog.strings ConfirmationDialog.xib
ibtool --export-strings-file DailyDevotion.strings DailyDevotion.xib
ibtool --export-strings-file DictionaryView.strings DictionaryView.xib
ibtool --export-strings-file ExtTextView.strings ExtTextView.xib
ibtool --export-strings-file GenBookView.strings GenBookView.xib
ibtool --export-strings-file InitialInfoView.strings InitialInfoView.xib
ibtool --export-strings-file LeftSideBarView.strings LeftSideBarView.xib
ibtool --export-strings-file MainMenu.strings MainMenu.xib
ibtool --export-strings-file ModuleListUI.strings ModuleListUI.xib
ibtool --export-strings-file ModuleManager.strings ModuleManager.xib
ibtool --export-strings-file ModuleManageView.strings ModuleManageView.xib
ibtool --export-strings-file NotesUI.strings NotesUI.xib
ibtool --export-strings-file NotesView.strings NotesView.xib
ibtool --export-strings-file Preferences.strings Preferences.xib
ibtool --export-strings-file PrintAccessory.strings PrintAccessory.xib
ibtool --export-strings-file ProgressOverlayView.strings ProgressOverlayView.xib
ibtool --export-strings-file RightSideBarView.strings RightSideBarView.xib
ibtool --export-strings-file SearchBookSetEditor.strings SearchBookSetEditor.xib
ibtool --export-strings-file SingleViewHost.strings SingleViewHost.xib
ibtool --export-strings-file ThreadedProgressSheet.strings ThreadedProgressSheet.xib
ibtool --export-strings-file WebView.strings WebView.xib
ibtool --export-strings-file WindowHostToolbar.strings WindowHostToolbar.xib
ibtool --export-strings-file WorkspaceViewHost.strings WorkspaceViewHost.xib
